# Generated by Django 6.0.4 on 2026-04-25 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_orderitem_product_alter_orderitem_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='checkout_id',
            field=models.UUIDField(db_index=True, default=1),
            preserve_default=False,
        ),
    ]
