# Generated by Django 6.0.4 on 2026-05-13 09:22

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_importjob_importedproducttracker_importlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importjob',
            name='csv_file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='imports/csv'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='importjob',
            name='zip_file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='imports/zip'), upload_to=''),
        ),
    ]
