# Generated by Django 6.0.4 on 2026-05-13 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_importjob_csv_file_alter_importjob_zip_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='public_id',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
